nebula:
  container:
    name: 3la-nebula
  image:
    repository: ghcr.io/3letteragency/nebula
    tag: v1.3.0
    pullPolicy: IfNotPresent
  deploymentName: nebula
  appSelector: nebula
  replicas: 1
  version: 1.3.0
  pki:
    ca: '/etc/nebula/ca.crt'
    cert: '/etc/nebula/host.crt'
    key: '/etc/nebula/host.key'
    blocklist: []
  static_host_map: {}
  lighthouse:
    am_lighthouse: false
    serve_dns: true
    dns:
      host: 0.0.0.0
      port: 53
    interval: 60
    hosts: []
    remote_allow_list: {}
    local_allow_list: {}
  listen:
    host: 0.0.0.0
    port: 4242
    batch: 64
    read_buffer: 10485760
    write_buffer: 10485760
  punchy:
    punch: true
    respond: true
    delay: 1s
  cipher: aes
  local_range: "10.0.0.0/24"
  sshd:
    enabled: true
    listen: 127.0.0.1:2222
    host_key: ./ssh_host_ecdsa_key
    authorized_users: []
    authorized_user: []
    authorized_keys: []
  tun:
    disabled: false
    dev: nebula1
    drop_local_broadcast: false
    drop_multicast: false
    tx_queue: 500
    mtu: 1300
    routes: []
    unsafe_routes: []
  logging:
    level: info
    format: text
  stats:
    type: prometheus
    listen: 127.0.0.1:8080
    path: /metrics
    namespace: prometheus
    subsystem: nebula
    interval: 10s
    message_metrics: false
    lighthouse_metrics: false
  firewall:
    conntrack:
      tcp_timeout: 12m
      udp_timeout: 3m
      default_timeout: 10m
      max_connections: 100000
    outbound: []
    inbound: []
